labels:
  'feature':
    - '^(feat):'
  'fix':
    - '^(fix):'
  'refactor':
    - '^(refactor):'
  'release':
    - '^(release):'
  'test':
    - '^(test):'
  'docs':
    - '^(docs):'
  'chore':
    - '^(chore):'
  'config':
    - '^(config):'
  'build':
    - '^(build):'