feature:
  - head-branch: ['^feat', 'feat']
fix:
  - head-branch: ['^fix', 'fix']
refactor:
  - head-branch: ['^refactor', 'refactor']
config:
  - head-branch: ['^config', 'config']
test:
  - head-branch: ['^test', 'test']
build:
  - head-branch: ['^build', 'build']
chore:
  - head-branch: ['^chore', 'chore']
release:
  - head-branch: ['^release', 'release']