spring:
  application:
    name: jobnote

  profiles:
    group:
      local: jwt
      test: jwt

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  security:
    whitelist:
      - /api/v1/users/signup
      - /api/v1/users/login
      - /api/v1/users/reissue