spring:
  application:
    name: jobnote

  profiles:
    group:
      local: jwt, mail
      test: jwt, mail

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

app:
  email-verification-path: /api/v1/users/verify